# Generated by Django 5.0.3 on 2024-03-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exams',
            name='duration',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='exams',
            name='passing_score',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='exams',
            name='no_of_questions',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='exams',
            name='total_score',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
