# Generated by Django 5.0.3 on 2024-04-01 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_rename_examsattended_examsresults'),
        ('register_login', '0002_studentdetails_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExamsResults',
            new_name='QuestionsAttended',
        ),
    ]
