# Generated by Django 5.0.3 on 2024-04-01 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_rename_examsresults_questionsattended'),
        ('register_login', '0002_studentdetails_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions_attempted', models.IntegerField(default=0, null=True)),
                ('score', models.IntegerField(default=0, null=True)),
                ('exam_status', models.CharField(blank=True, max_length=100, null=True)),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.exams')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='register_login.studentdetails')),
            ],
        ),
    ]
